# Generated by Django 5.2.1 on 2025-06-06 05:00

import nopassword.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nopassword', '0002_logincode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logincode',
            name='expires_at',
            field=models.DateTimeField(default=nopassword.models.default_expiry, editable=False, null=True),
        ),
    ]