# Generated by Django 5.2.1 on 2025-07-22 19:09 and edited by Raul

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nopassword', '0005_logincode_populate_uuid_and_swap_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logincode',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=128),
            preserve_default=False,
        ),
    ]
