# Generated by Django 5.2.4 on 2025-09-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nopassword', '0006_logincode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logincode',
            name='code',
            field=models.CharField(editable=False, max_length=6),
        ),
    ]
